### ISSUE TITLE
Default query

### ISSUE THREAD

**Issue by dgastudio** [betagouv/react-elasticsearch#39]
Hello
i'm trying to run your module based on 
https://codesandbox.io/s/7yevo

but, it's showing 0 results by default

in provided sandbox where are a customQueryMovie function, but i can't found the way it's usage

can you provide, please, an example of how to show all results be default?

thank you

**Comment by rap2hpoutre** [comment]
Thank you for your contribution and sorry for super late answer. It just has been fixed in v3.0.1.
